spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret
  redis:
    host: 127.0.0.1
    port: 6379

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
  redis:
    host: 43.202.230.185
    port: 6379

server:
  port: 8080
  deploy-address: localhost
  name: local


---

spring:
  config:
    activate:
      on-profile: blue
  redis:
    host: 43.202.230.185
    port: 6379

server:
  port: 8080
  deploy-address: 43.202.230.185
  name: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  redis:
    host: 43.202.230.185
    port: 6379

server:
  port: 9090
  deploy-address: 43.202.230.185
  name: green_server

---

client:
  deploy-address: "localhost:3000"

mybatis:
  mapper-locations:
    - /mappers/*.xml